### ISSUE TITLE
Minor issue with ext8

### ISSUE THREAD

**Issue by vector76** [bastibe/matlab-msgpack#1]
First, thank you for this Matlab msgpack parser, I am finding it tremendously useful.

I found (and fixed) a couple minor issues I wanted to share.  I'm not set up to submit pull requests so I will just describe it:

Lines 175 and 176 within parsemsgpack.m appears to be a simple typo, should be "out.type" and "out.data", or else it complains "output argument not assigned"

Also, line 85 for parsing ext8 should be idx+2, not idx+1.  Here is an example ext8 of 20 bytes of type 2:
test = uint8([199 20 2 0 0 128 63 0 0 0 64 0 0 96 64 0 0 144 64 20 174 191 64]);
and without the fix (idx+2 instead of idx+1) it attempts to use 20 as the first byte of the content.

Again thanks for this implementation, I hope this is helpful.

**Comment by bastibe** [comment]
Thank you for the bug report and fixes!

I'd prefer a pull request to be honest. Did you know that you can create a pull request right here in the web interface of Github? Just go to the file you want to change, and click the little pen icon at the top right, next to the "Raw/Blame/History" buttons.

If you still prefer me to do it, that is fine, too, of course.

**Comment by vector76** [comment]
Cool, I didn't know that.  That's a neat feature that makes it much easier.
