### ISSUE TITLE
The code is not working properly.

### ISSUE THREAD

**Issue by daoerb** [bastibe/matlab-msgpack#9]
data = {'life, the universe, and everything', struct('the_answer', 42)};
bytes = dumpmsgpack(data)
data = parsemsgpack(bytes)
% returns: {'life, the universe, and everything', containers.Map('the_answer', 42)}

data =
  1×2 cell 数组
    {'life, the universe, and everything'}    {1×1 containers.Map}
![image](https://github.com/user-attachments/assets/c88adf11-d320-4b3e-9ce7-59905cec54bd)
Matlab 2022a test failed!

**Comment by bastibe** [comment]
This is working as intended. Structs can not hold arbitrary strings, and are thus unsuited for MsgPack maps. As the readme and documentation states, we therefore use containers.Map instead.
